" appearance
set number
set hlsearch
set cursorline
colorscheme molokai
syntax on

" format
set autoindent
set shiftwidth=4
set tabstop=4
set softtabstop=4
set expandtab
set encoding=utf-8
set fileencoding=utf-8
set fileformat=unix

" key config
" normal mapping
nmap <C-K> <C-V>
nmap <F5> <ESC> :NERDTreeToggle<CR> 
nmap <F6> <ESC> :TagbarToggle<CR>
nmap ftn :FloatermNew<CR>
nmap ftt :FloatermToggle<CR>
nmap ftk :FloatermKill<CR>
nmap ftm :FloatermNew make<CR>

" enable mouse
set mouse=a

" vim-plug
call plug#begin('~/.vim/plugged')
Plug 'preservim/tagbar'
Plug 'preservim/nerdtree'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'ludovicchabant/vim-gutentags'
Plug 'skywind3000/gutentags_plus'
Plug 'voldikss/vim-floaterm'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
call plug#end()

" nerdTree
let g:NERDTreeWinPos="left"

" coc.nvim
inoremap <silent><expr> <TAB>
      \ coc#pum#visible() ? coc#pum#next(1) :
      \ CheckBackspace() ? "\<Tab>" :
      \ coc#refresh()
inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"
inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm()
                              \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
function! CheckBackspace() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

" gtags
set cscopetag

" gutentags
let g:gutentags_project_root = ['.root', '.svn', '.git', '.hg', '.project']
let g:gutentags_ctags_tagfile = '.tags'
let g:gutentags_modules = []
if executable('ctags')
	let g:gutentags_modules += ['ctags']
endif
if executable('gtags-cscope') && executable('gtags')
	let g:gutentags_modules += ['gtags_cscope']
endif
let g:gutentags_cache_dir = expand('~/.cache/tags')
let g:gutentags_ctags_extra_args = ['--fields=+niazS', '--extra=+q']
let g:gutentags_ctags_extra_args += ['--c++-kinds=+px']
let g:gutentags_ctags_extra_args += ['--c-kinds=+px']
let g:gutentags_ctags_extra_args += ['--output-format=e-ctags']
